# Generated by Django 4.0.3 on 2022-03-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_delete_campusfleet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuingEducationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('continuing_education_course_title', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSustGrpProgInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('student_sust_grp_prog_initiative_type', models.CharField(max_length=500)),
                ('student_sust_grp_prog_initiative_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=15)),
                ('description_of_measureable_impacts', models.CharField(max_length=255)),
                ('supporting_outreact_materials', models.BooleanField(default=False)),
                ('supporting_outreact_materials_description', models.CharField(blank=True, max_length=255, null=True)),
                ('student_sust_grp_prog_initiative_url', models.URLField(blank=True, max_length=255, null=True)),
                ('supporting_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfessionalDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('staff_professional_development_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('dates_offered', models.CharField(max_length=100)),
                ('num_of_staff_participants', models.IntegerField()),
                ('internally_or_externally_funded', models.CharField(max_length=100)),
                ('staff_professional_development_url', models.URLField(blank=True, max_length=255, null=True)),
                ('supporting_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
        migrations.CreateModel(
            name='PeerToPeerOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('peer_to_peer_outreach_type', models.TextField(max_length=100)),
                ('peer_to_peer_outreach_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('educators_training', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=255)),
                ('program_starting_date', models.DateField()),
                ('program_status', models.CharField(max_length=10)),
                ('num_actively_trained_educators', models.IntegerField()),
                ('num_weeks_program_is_active_annually', models.IntegerField()),
                ('num_hours_worked_weekly_per_trained_educators', models.IntegerField()),
                ('num_hours_worked_annualy_by_trained_educators', models.IntegerField()),
                ('program_url', models.URLField(blank=True, max_length=255, null=True)),
                ('supporting_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('community_partnership_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('supported', models.BooleanField(default=False)),
                ('timeframe', models.CharField(max_length=50)),
                ('type_of_partnership', models.CharField(max_length=100)),
                ('vulnerable_population_engagement', models.BooleanField(default=True)),
                ('community_partnership_url', models.URLField(blank=True, max_length=255, null=True)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityEducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('ce_program_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('semester_program_started', models.CharField(max_length=100)),
                ('year_program_started', models.CharField(max_length=10)),
                ('program_status', models.CharField(max_length=10)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
    ]
