# Generated by Django 4.0.3 on 2022-03-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0003_alter_peertopeeroutreach_reporting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuingeducationcourse',
            old_name='year',
            new_name='academic_year',
        ),
        migrations.AlterField(
            model_name='communityeducationprogram',
            name='reporting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='communitypartnership',
            name='reporting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='continuingeducationcourse',
            name='reporting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffprofessionaldevelopment',
            name='reporting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentsustgrpproginitiative',
            name='reporting_date',
            field=models.DateField(),
        ),
    ]
