# Generated by Django 4.0.3 on 2022-03-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0004_rename_year_continuingeducationcourse_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsustgrpproginitiative',
            old_name='supporting_outreact_materials',
            new_name='supporting_outreach_materials',
        ),
        migrations.RenameField(
            model_name='studentsustgrpproginitiative',
            old_name='supporting_outreact_materials_description',
            new_name='supporting_outreach_materials_description',
        ),
    ]
