# Generated by Django 4.0.3 on 2022-03-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0005_rename_supporting_outreact_materials_studentsustgrpproginitiative_supporting_outreach_materials_and_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuingeducationcourse',
            old_name='semester',
            new_name='semester_offered',
        ),
    ]
