# Generated by Django 4.0.3 on 2022-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0006_rename_semester_continuingeducationcourse_semester_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationcourse',
            name='semester_offered',
            field=models.CharField(max_length=15),
        ),
    ]
