# Generated by Django 4.0.3 on 2022-04-06 20:50

import campusandcommunity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0007_alter_continuingeducationcourse_semester_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peertopeeroutreach',
            name='supporting_doc',
        ),
        migrations.RemoveField(
            model_name='staffprofessionaldevelopment',
            name='supporting_doc',
        ),
        migrations.RemoveField(
            model_name='studentsustgrpproginitiative',
            name='supporting_doc',
        ),
        migrations.AddField(
            model_name='peertopeeroutreach',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to=campusandcommunity.models.upload_file),
        ),
        migrations.AddField(
            model_name='staffprofessionaldevelopment',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to=campusandcommunity.models.upload_file),
        ),
        migrations.AddField(
            model_name='studentsustgrpproginitiative',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to=campusandcommunity.models.upload_file),
        ),
    ]
