# Generated by Django 4.0.3 on 2022-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0009_remove_communityeducationprogram_poc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityeducationprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='communitypartnership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='peertopeeroutreach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffprofessionaldevelopment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentsustgrpproginitiative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
