# Generated by Django 4.0.3 on 2022-04-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0011_continuingeducationcourse_college_or_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsustgrpproginitiative',
            name='target_audience',
            field=models.CharField(max_length=255),
        ),
    ]
