# Generated by Django 4.0.3 on 2022-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0012_alter_studentsustgrpproginitiative_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityeducationprogram',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='communitypartnership',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='continuingeducationcourse',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='peertopeeroutreach',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='staffprofessionaldevelopment',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='studentsustgrpproginitiative',
            name='reporting_date',
        ),
        migrations.AddField(
            model_name='communityeducationprogram',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communitypartnership',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='continuingeducationcourse',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='peertopeeroutreach',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofessionaldevelopment',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsustgrpproginitiative',
            name='reporting_academic_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
