# Generated by Django 4.0.3 on 2022-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0015_staffprofessionaldevelopment_externally_funded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityeducationprogram',
            name='reporting_academic_year',
        ),
        migrations.RemoveField(
            model_name='communitypartnership',
            name='reporting_academic_year',
        ),
        migrations.RemoveField(
            model_name='continuingeducationcourse',
            name='reporting_academic_year',
        ),
        migrations.RemoveField(
            model_name='peertopeeroutreach',
            name='reporting_academic_year',
        ),
        migrations.RemoveField(
            model_name='staffprofessionaldevelopment',
            name='reporting_academic_year',
        ),
        migrations.RemoveField(
            model_name='studentsustgrpproginitiative',
            name='reporting_academic_year',
        ),
        migrations.AddField(
            model_name='communityeducationprogram',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityeducationprogram',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypartnership',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitypartnership',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuingeducationcourse',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuingeducationcourse',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peertopeeroutreach',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peertopeeroutreach',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofessionaldevelopment',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofessionaldevelopment',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsustgrpproginitiative',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsustgrpproginitiative',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
