# Generated by Django 4.0.3 on 2022-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodandwaste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbeveragepurchasing',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='foodbeveragepurchasing',
            name='reporting_period_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='foodbeveragepurchasing',
            name='reporting_period_start_date',
            field=models.DateField(null=True),
        ),
    ]
