# Generated by Django 4.0.3 on 2022-06-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodandwaste', '0003_foodbeveragepurchasing_reporting_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbeveragepurchasing',
            name='reporting_academic_year',
        ),
    ]
