# Generated by Django 4.0.3 on 2022-03-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airandtransportation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusfleet',
            old_name='cum_hudrogen_vehicles',
            new_name='num_hudrogen_vehicles',
        ),
    ]
