# Generated by Django 4.0.3 on 2022-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airandtransportation', '0003_rename_num_hudrogen_vehicles_campusfleet_num_hydrogen_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusfleet',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='campusfleet',
            name='reporting_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campusfleet',
            name='reporting_period_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
