# Generated by Django 4.0.3 on 2022-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airandtransportation', '0005_remove_campusfleet_campus_fleet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusfleet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
