# Generated by Django 4.0.3 on 2022-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airandtransportation', '0007_campusfleet_reporting_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusfleet',
            name='reporting_academic_year',
        ),
    ]
