# Generated by Django 4.0.3 on 2022-03-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSustGrpProgInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('student_sust_grp_prog_initiative_type', models.CharField(max_length=500)),
                ('student_sust_grp_prog_initiative_title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('target_audience', models.CharField(max_length=15)),
                ('description_of_measureable_impacts', models.CharField(max_length=255)),
                ('supporting_outreact_materials', models.BooleanField(default=False)),
                ('supporting_outreact_materials_description', models.CharField(blank=True, max_length=255, null=True)),
                ('student_sust_grp_prog_initiative_url', models.URLField(blank=True, max_length=255, null=True)),
                ('supporting_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('poc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.poc')),
            ],
        ),
    ]
