# Generated by Django 4.0.3 on 2022-03-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_acadmeiccourse_academiccourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampusFleet',
        ),
        migrations.RemoveField(
            model_name='communityeducationprogram',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='communitypartnership',
            name='poc',
        ),
        migrations.DeleteModel(
            name='ContinuingEducationCourse',
        ),
        migrations.DeleteModel(
            name='FacultySustResearchAndService',
        ),
        migrations.DeleteModel(
            name='FoodBeveragePurchasing',
        ),
        migrations.RemoveField(
            model_name='peertopeeroutreach',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='staffprofessionaldevelopment',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='studentsustgrpproginitiative',
            name='poc',
        ),
        migrations.DeleteModel(
            name='CommunityEducationProgram',
        ),
        migrations.DeleteModel(
            name='CommunityPartnership',
        ),
        migrations.DeleteModel(
            name='PeerToPeerOutreach',
        ),
        migrations.DeleteModel(
            name='StaffProfessionalDevelopment',
        ),
        migrations.DeleteModel(
            name='StudentSustGrpProgInitiative',
        ),
    ]
