# Generated by Django 4.0.3 on 2022-03-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_rename_reporting_date_academicprogram_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogram',
            name='reporting_date',
            field=models.DateField(null=True),
        ),
    ]
