# Generated by Django 4.0.3 on 2022-03-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_academicprogram_reporting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusaslivinglab',
            old_name='type_of_project',
            new_name='project_type',
        ),
    ]
