# Generated by Django 4.0.3 on 2022-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_rename_type_of_project_campusaslivinglab_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusaslivinglab',
            name='project_date',
            field=models.DateField(),
        ),
    ]
