# Generated by Django 4.0.3 on 2022-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_campusaslivinglab_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprogram',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='campusaslivinglab',
            name='academic_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
