# Generated by Django 4.0.3 on 2022-04-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_rename_semester_program_started_academicprogram_semester_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusaslivinglab',
            name='relative_doc',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
