# Generated by Django 4.0.3 on 2022-04-06 20:26

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_campusaslivinglab_relative_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusaslivinglab',
            name='relative_doc',
        ),
        migrations.AddField(
            model_name='campusaslivinglab',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to=curriculum.models.upload_file),
        ),
    ]
