# Generated by Django 4.0.3 on 2022-04-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusandcommunity', '0009_remove_communityeducationprogram_poc_and_more'),
        ('curriculum', '0013_remove_campusaslivinglab_relative_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprogram',
            name='poc',
        ),
        migrations.RemoveField(
            model_name='campusaslivinglab',
            name='poc',
        ),
        migrations.AddField(
            model_name='academiccourse',
            name='college_or_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='poc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='poc_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campusaslivinglab',
            name='poc_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campusaslivinglab',
            name='poc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campusaslivinglab',
            name='poc_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='academiccourse',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='college_or_unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='POC',
        ),
    ]
