# Generated by Django 4.0.3 on 2022-04-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_remove_academiccourse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusaslivinglab',
            name='contribution_to_impact_area',
            field=models.CharField(max_length=200),
        ),
    ]
