# Generated by Django 4.0.3 on 2022-05-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_alter_campusaslivinglab_contribution_to_impact_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccourse',
            old_name='year_offered',
            new_name='reporting_academic_year',
        ),
        migrations.RenameField(
            model_name='academiccourse',
            old_name='semester_offered',
            new_name='sections_offered',
        ),
    ]
