# Generated by Django 4.0.3 on 2022-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_remove_academicprogram_reporting_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campusaslivinglab',
            old_name='academic_year',
            new_name='reporting_academic_year',
        ),
    ]
