# Generated by Django 4.0.3 on 2022-06-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_remove_academiccourse_reporting_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academiccourse',
            old_name='reporting_end_date',
            new_name='reporting_period_end_date',
        ),
        migrations.RenameField(
            model_name='academiccourse',
            old_name='reporting_start_date',
            new_name='reporting_period_start_date',
        ),
        migrations.RenameField(
            model_name='academicprogram',
            old_name='reporting_end_date',
            new_name='reporting_period_end_date',
        ),
        migrations.RenameField(
            model_name='academicprogram',
            old_name='reporting_start_date',
            new_name='reporting_period_start_date',
        ),
        migrations.RenameField(
            model_name='campusaslivinglab',
            old_name='reporting_end_date',
            new_name='reporting_period_end_date',
        ),
        migrations.RenameField(
            model_name='campusaslivinglab',
            old_name='reporting_start_date',
            new_name='reporting_period_start_date',
        ),
    ]
