# Generated by Django 4.0.3 on 2022-03-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySustResearchAndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(auto_now_add=True)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_email', models.EmailField(max_length=100)),
                ('department_affiliation', models.CharField(max_length=100)),
                ('sust_research_area', models.CharField(max_length=100)),
                ('research_interests', models.CharField(max_length=255)),
                ('research_published', models.CharField(max_length=20)),
                ('publication_title', models.CharField(blank=True, max_length=30, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=30, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_deposited', models.BooleanField(blank=True, default=False, null=True)),
                ('presented_research_at_sust_conference', models.BooleanField(blank=True, default=False, null=True)),
                ('sust_research_conf_description', models.TextField(blank=True, null=True)),
                ('sust_research_service_dates', models.CharField(blank=True, max_length=100, null=True)),
                ('support_url', models.URLField(blank=True, max_length=255, null=True)),
                ('supporting_document', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
