# Generated by Django 4.0.3 on 2022-03-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0002_rename_journal_name_facultysustresearchandservice_journal_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultysustresearchandservice',
            name='supporting_document',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
