# Generated by Django 4.0.3 on 2022-04-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0011_rename_journal_detail_facultysustresearchandservice_journal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
