# Generated by Django 4.0.3 on 2022-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0012_facultysustresearchandservice_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultysustresearchandservice',
            old_name='reporting_date',
            new_name='project_date',
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='reporting_academic_year',
            field=models.CharField(default='FY22', max_length=20),
            preserve_default=False,
        ),
    ]
