# Generated by Django 4.0.3 on 2022-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0013_rename_reporting_date_facultysustresearchandservice_project_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='date_of_publication',
        ),
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='journal_name',
        ),
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='publication_title',
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='publication_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
