# Generated by Django 4.0.3 on 2022-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0014_remove_facultysustresearchandservice_date_of_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='department_affiliation',
        ),
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='project_date',
        ),
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='abstract_summary_project',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='college_or_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='list_names_faculty_collab',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='project_conducted_collab_uhcl_faculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='title_research_project',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
