# Generated by Django 4.0.3 on 2022-06-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0016_facultysustresearchandservice_grant_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='additional_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
