# Generated by Django 4.0.3 on 2022-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchscholarship', '0017_facultysustresearchandservice_additional_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultysustresearchandservice',
            name='reporting_academic_year',
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='reporting_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='facultysustresearchandservice',
            name='reporting_start_date',
            field=models.DateField(null=True),
        ),
    ]
